### ISSUE TITLE
Not working on windows platform for chromium based browsers

### ISSUE THREAD

**Issue by gameonvinay** [thekelvinliu/country-code-emoji#24] opened 2022-10-07 06:09 UTC

**Comment by stof** [comment] 2023-01-10 10:16
The issue is not that the library is not working but that the Segoe UI Emoji (the builtin emoji font on windows) does not support flags. See https://stackoverflow.com/a/54520964

**Comment by roderickhsiao** [comment] 2023-03-20 18:44
some fallback solution https://yarnpkg.com/package/country-flag-emoji-polyfill

**Comment by thekelvinliu** [comment] 2023-04-07 18:20
ty @stof 😄 

closing bc out of scope

**Closed as not planned by thekelvinliu** 2023-04-07 18:20 UTC
